-- ============================================================
-- IlDisagio — Seed database: 160 disagi iniziali
-- Tutti approvati, punteggio Elo 1000, lingua italiana
-- ============================================================

INSERT INTO disagi (testo, categoria, lingua, stato) VALUES

-- SOCIALE (30)
('Salutare qualcuno convintissimo e accorgersi che stava salutando quello dietro di te.', 'sociale', 'it', 'approvato'),
('Dire "anche tu" a qualcuno che ti ha appena detto buon appetito.', 'sociale', 'it', 'approvato'),
('Incrociare qualcuno per strada, spostarsi a destra, lui si sposta a sinistra, fare la danza degli imbecilli per 4 secondi eterni.', 'sociale', 'it', 'approvato'),
('Rispondere "bene grazie" a qualcuno che ti ha chiesto cosa hai preso al bar.', 'sociale', 'it', 'approvato'),
('Alzare la mano per salutare qualcuno che ti guarda dritto ma in realtà saluta qualcun altro.', 'sociale', 'it', 'approvato'),
('Ridere a una battuta che non hai capito e poi doverti impegnare a sembrare che l''avessi capita.', 'sociale', 'it', 'approvato'),
('Chiamare per sbaglio un professore "mamma".', 'sociale', 'it', 'approvato'),
('Aprire la porta di un bagno occupato. Guardare negli occhi. Richiudere.', 'sociale', 'it', 'approvato'),
('Fare una risata finta perché non hai capito la battuta e poi scoprire che non era una battuta.', 'sociale', 'it', 'approvato'),
('Rispondere a "ciao come stai" con un monologo di dieci minuti quando l''altro si aspettava solo "bene grazie e tu".', 'sociale', 'it', 'approvato'),
('Finire di salutare qualcuno e poi camminare nella stessa direzione per due minuti in silenzio.', 'sociale', 'it', 'approvato'),
('Pensare di essere in silenzioso vivavoce e scoprire di no.', 'sociale', 'it', 'approvato'),
('Dire addio a qualcuno e poi ritrovarti a camminare nella stessa direzione.', 'sociale', 'it', 'approvato'),
('Fare la battuta del gruppo e non ridere nessuno. Neanche tu, da quel momento.', 'sociale', 'it', 'approvato'),
('Bussare a una porta aperta e non sapere se bussare ancora o entrare.', 'sociale', 'it', 'approvato'),
('Scambiare un negozio per un altro e salutare entusiasta persone che non conosci.', 'sociale', 'it', 'approvato'),
('Fare una faccia strana mentre rileggi un messaggio e renderti conto che ti stavano guardando.', 'sociale', 'it', 'approvato'),
('Aspettare che qualcuno finisca una frase e realizzare che aveva già finito da dieci secondi.', 'sociale', 'it', 'approvato'),
('Ridere di una storia che stai raccontando tu prima di arrivare al punto divertente.', 'sociale', 'it', 'approvato'),
('Rispondere a una notifica del telefono e scoprire che era una pubblicità.', 'sociale', 'it', 'approvato'),
('Salutare con troppa energia qualcuno che non ti ricordavi assolutamente.', 'sociale', 'it', 'approvato'),
('Andare verso la porta di uscita mentre stai chiacchierando con qualcuno e rimanere a chiacchierare per altri venti minuti.', 'sociale', 'it', 'approvato'),
('Parlare male di qualcuno e sentire il telefono che ronza: è quella persona che ti ha appena scritto.', 'sociale', 'it', 'approvato'),
('Fare finta di guardare il telefono per non dover salutare qualcuno che hai già salutato tre volte oggi.', 'sociale', 'it', 'approvato'),
('Rispondere "benissimo" alla domanda "hai sentito?" di chi ti stava spiegando qualcosa.', 'sociale', 'it', 'approvato'),
('Salutare troppo entusiasta qualcuno che invece ti saluta con distacco, e non poter tornare indietro.', 'sociale', 'it', 'approvato'),
('Iniziare a raccontare una storia e realizzare a metà che l''hai già raccontata a questa persona.', 'sociale', 'it', 'approvato'),
('Prendere confidenza con qualcuno troppo in fretta e poi imbarazzarti di te stesso.', 'sociale', 'it', 'approvato'),
('Fare una domanda retorica e aspettarti silenziosa approvazione, ricevere invece una risposta dettagliata di sette minuti.', 'sociale', 'it', 'approvato'),
('Dire "buonanotte" a qualcuno alle tre del pomeriggio per puro automatismo.', 'sociale', 'it', 'approvato'),

-- DIGITALE (28)
('Mandare un messaggio vocale di due minuti e realizzare subito dopo che potevi scrivere "ok".', 'digitale', 'it', 'approvato'),
('Rileggere un messaggio mandato tre anni fa e passare i dieci minuti successivi a riflettere su chi eri.', 'digitale', 'it', 'approvato'),
('Rispondere "lol" a un messaggio di condoglianze perché stavi scrivendo a qualcun altro.', 'digitale', 'it', 'approvato'),
('Iniziare a scrivere un messaggio, cancellarlo, riscriverlo e alla fine mandare solo "ok".', 'digitale', 'it', 'approvato'),
('Aprire una chat, non sapere cosa rispondere, chiuderla, riaprirla tre ore dopo. Ancora niente.', 'digitale', 'it', 'approvato'),
('Scrivere un messaggio lunghissimo e poi premere annulla perché ti sei reso conto di essere ridicolo.', 'digitale', 'it', 'approvato'),
('Mandare per sbaglio uno screenshot della conversazione alla persona di cui stai parlando.', 'digitale', 'it', 'approvato'),
('Vedere le due spunte blu e aspettare la risposta per ore. La risposta non arriva.', 'digitale', 'it', 'approvato'),
('Postare una storia su Instagram e poi rimuoverla dopo trenta secondi perché "non era il momento".', 'digitale', 'it', 'approvato'),
('Mettere like a una foto di tre anni fa di qualcuno che stavi guardando un po'' troppo.', 'digitale', 'it', 'approvato'),
('Lasciare un commento su un post del 2019 e ricevere la notifica "ha messo mi piace al tuo commento" di notte.', 'digitale', 'it', 'approvato'),
('Scrivere un messaggio al gruppo sbagliato. Guardare il telefono. Non poter fare niente.', 'digitale', 'it', 'approvato'),
('Mandare un meme senza testo e aspettare cinque minuti la risposta per poi ricevere solo "?".', 'digitale', 'it', 'approvato'),
('Fare una chiamata, non sapere come iniziare, stare in silenzio per tre secondi, dire "allora".', 'digitale', 'it', 'approvato'),
('Rispondere a una storia di qualcuno che non ti segue più. La risposta resta in sospeso.', 'digitale', 'it', 'approvato'),
('Aprire Google Maps e camminare cinquanta metri nella direzione sbagliata prima che si aggiorni.', 'digitale', 'it', 'approvato'),
('Scrivere "arrivo tra cinque minuti" quando sei ancora a casa.', 'digitale', 'it', 'approvato'),
('Partecipare a una call di lavoro con il microfono spento per cinque minuti senza saperlo.', 'digitale', 'it', 'approvato'),
('Iniziare a registrare un vocale, sbagliare tutto, cancellare, ricominciare quattro volte.', 'digitale', 'it', 'approvato'),
('Leggere un messaggio, pensare di rispondere dopo, dimenticartelo per tre giorni.', 'digitale', 'it', 'approvato'),
('Ricevere uno screenshot di una conversazione su di te da parte della persona di cui stai parlando.', 'digitale', 'it', 'approvato'),
('Seguire per sbaglio qualcuno sui social mentre stavi guardando il profilo. Unfollow immediato. Ma loro l''hanno già visto.', 'digitale', 'it', 'approvato'),
('Commentare con un emoji il post sbagliato in un gruppo di lavoro.', 'digitale', 'it', 'approvato'),
('Rispondere alla mail di tutti invece di solo al mittente.', 'digitale', 'it', 'approvato'),
('Mandare un messaggio e poi renderti conto che il testo predittivo ha cambiato tutto il senso.', 'digitale', 'it', 'approvato'),
('Aprire Instagram, guardare trenta storie, mettere il telefono giù. Non sai cosa hai visto.', 'digitale', 'it', 'approvato'),
('Scrivere un commento lungo e articolato, postarlo, e subito dopo trovare un errore madornale.', 'digitale', 'it', 'approvato'),
('Mandare un vocale al contatto sbagliato e passare i successivi dieci minuti a sperare che non lo apra.', 'digitale', 'it', 'approvato'),

-- RELAZIONALE (27)
('Rileggere vecchi messaggi e accorgersi che il problema eri tu.', 'relazionale', 'it', 'approvato'),
('Fare una confessione emotiva e ricevere in risposta "haha sì".', 'relazionale', 'it', 'approvato'),
('Raccontare un segreto giurando "non lo dire a nessuno" a qualcuno che lo dirà sicuramente.', 'relazionale', 'it', 'approvato'),
('Ricordare di aver detto qualcosa di stupido a qualcuno cinque anni fa e non riuscire ad addormentarti.', 'relazionale', 'it', 'approvato'),
('Aspettare di essere aggiunto a un gruppo WhatsApp e non venire aggiunto.', 'relazionale', 'it', 'approvato'),
('Fare una battuta ironica e vederla prendere sul serio nel modo peggiore possibile.', 'relazionale', 'it', 'approvato'),
('Ricordare improvvisamente a caso qualcosa di imbarazzante di dieci anni fa mentre stai aspettando l''autobus.', 'relazionale', 'it', 'approvato'),
('Essere la persona che risponde al messaggio del gruppo tre ore dopo quando la conversazione è già finita.', 'relazionale', 'it', 'approvato'),
('Stare in silenzio in una conversazione di gruppo perché non sai come inserirsi e venire direttamente interpellato.', 'relazionale', 'it', 'approvato'),
('Scoprire di essere stato l''unico del gruppo a non essere invitato.', 'relazionale', 'it', 'approvato'),
('Mandare un messaggio a qualcuno con cui hai litigato, eliminarlo subito, ma lui l''ha già letto.', 'relazionale', 'it', 'approvato'),
('Raccontare qualcosa con entusiasmo e accorgersi che l''altro lo sapeva già da tempo.', 'relazionale', 'it', 'approvato'),
('Fare una domanda e capire dalla risposta che stavi parlando con la persona sbagliata da tutto il tempo.', 'relazionale', 'it', 'approvato'),
('Invitare qualcuno a qualcosa e ricevere un "forse" che entrambi sapete che significa no.', 'relazionale', 'it', 'approvato'),
('Ricordare il compleanno di qualcuno troppo tardi per mandare un messaggio in orario e decidere di non mandarlo.', 'relazionale', 'it', 'approvato'),
('Cercare di consolare qualcuno e capire a metà frase che stai dicendo la cosa sbagliata.', 'relazionale', 'it', 'approvato'),
('Fare una domanda personale e realizzare solo dopo che era troppo personale.', 'relazionale', 'it', 'approvato'),
('Ammettere di non aver guardato la serie di cui tutti parlano e sentire il silenzio che cade.', 'relazionale', 'it', 'approvato'),
('Mandare un messaggio ironico a qualcuno che non capisce l''ironia.', 'relazionale', 'it', 'approvato'),
('Dimenticarsi il nome di qualcuno a metà conversazione e dover evitare di usarlo per tutto il tempo.', 'relazionale', 'it', 'approvato'),
('Scoprire che qualcuno ti ha rimosso dagli amici e stare male senza sapere perché.', 'relazionale', 'it', 'approvato'),
('Ricevere il "visto" a un messaggio e nessuna risposta. Aspettare. Niente.', 'relazionale', 'it', 'approvato'),
('Condividere un''opinione e scoprire che tutti nel gruppo la pensano diversamente.', 'relazionale', 'it', 'approvato'),
('Fare una cosa gentile che viene interpretata come maleducazione.', 'relazionale', 'it', 'approvato'),
('Ringraziarsi a vicenda all''infinito senza riuscire a chiudere la conversazione.', 'relazionale', 'it', 'approvato'),
('Mentire per stare a casa e poi vedere le foto della serata sui social.', 'relazionale', 'it', 'approvato'),
('Essere sicurissimo che qualcuno ti stia antipatico e poi scoprire che ti ha sempre stimato molto.', 'relazionale', 'it', 'approvato'),

-- PUBBLICO (26)
('Entrare in una stanza con un obiettivo preciso e uscirne con una pera.', 'pubblico', 'it', 'approvato'),
('Ridere forte e solo in un cinema silenzioso.', 'pubblico', 'it', 'approvato'),
('Tirare una porta da spingere. Spingere una porta da tirare. Ripetere.', 'pubblico', 'it', 'approvato'),
('Camminare verso qualcuno convinto che si sposterebbe lui, non sposta, devi spostarti tu all''ultimo secondo.', 'pubblico', 'it', 'approvato'),
('Inciampare su un marciapiede piano e fare quel mezzo passo veloce per recuperare l''equilibrio mentre tutti guardano.', 'pubblico', 'it', 'approvato'),
('Pensare che il semaforo fosse verde e partire. Non era verde.', 'pubblico', 'it', 'approvato'),
('Scendere dall''autobus alla fermata sbagliata e dover aspettare il prossimo davanti a tutti quelli che hai salutato.', 'pubblico', 'it', 'approvato'),
('Cercare il telefono in tutte le tasche in fila al supermercato mentre dietro di te si allunga la coda.', 'pubblico', 'it', 'approvato'),
('Aprire la borsa per pagare e far cadere tutto per terra davanti alla cassa.', 'pubblico', 'it', 'approvato'),
('Perdere i biglietti del bus nel momento esatto in cui arriva il controllore.', 'pubblico', 'it', 'approvato'),
('Sederti su una sedia che cigola ogni volta che ti muovi durante una riunione in silenzio.', 'pubblico', 'it', 'approvato'),
('Tossire in un momento silenzioso e poi non riuscire a smettere.', 'pubblico', 'it', 'approvato'),
('Stare in piedi sull''autobus e cadere addosso a qualcuno alla prima frenata.', 'pubblico', 'it', 'approvato'),
('Arrivare in ritardo a una riunione e fare rumore con la sedia mentre tutti ti guardano sederti.', 'pubblico', 'it', 'approvato'),
('Fare una domanda al professore e capire a metà che la risposta era nell''ultima slide.', 'pubblico', 'it', 'approvato'),
('Essere convinto di ricordare dove hai parcheggiato. Non lo ricordi.', 'pubblico', 'it', 'approvato'),
('Sbagliare piano con l''ascensore e dover aspettare in silenzio accanto a chi ti ha visto sbagliare.', 'pubblico', 'it', 'approvato'),
('Fare la fila al self-checkout e avere l''articolo non riconosciuto mentre tutti aspettano.', 'pubblico', 'it', 'approvato'),
('Applaudire dopo un concerto e smettere troppo presto. Tutti gli altri continuano.', 'pubblico', 'it', 'approvato'),
('Sederti nel posto sbagliato al cinema e doverti alzare quando arriva il proprietario.', 'pubblico', 'it', 'approvato'),
('Fare una domanda a un commesso che non è un commesso.', 'pubblico', 'it', 'approvato'),
('Parlare con qualcuno che stai pensando stia parlando con te e poi vedere il suo auricolare.', 'pubblico', 'it', 'approvato'),
('Fare un gesto con la mano mentre parli al telefono come se l''altro ti vedesse.', 'pubblico', 'it', 'approvato'),
('Ridere al telefono in pubblico e incrociare lo sguardo di qualcuno che non sa perché ridi.', 'pubblico', 'it', 'approvato'),
('Perdere l''equilibrio alzandoti dalla sedia durante una lezione e agitare le braccia per recuperarlo.', 'pubblico', 'it', 'approvato'),
('Essere l''unico a non capire un annuncio alla stazione e dover seguire gli altri a caso.', 'pubblico', 'it', 'approvato'),

-- LAVORO (25)
('Presentare il progetto sbagliato in una riunione importante.', 'lavoro', 'it', 'approvato'),
('Mandare una mail con "in allegato trovate" senza allegato. Accorgersene dopo dieci minuti.', 'lavoro', 'it', 'approvato'),
('Fare una battuta in una call di lavoro e sentire silenzio assoluto.', 'lavoro', 'it', 'approvato'),
('Arrivare a una riunione e scoprire che era stata spostata un''ora prima.', 'lavoro', 'it', 'approvato'),
('Chiamarsi con il capo per discutere di qualcosa che si è già risolto da solo.', 'lavoro', 'it', 'approvato'),
('Mandare una mail di lamentela al diretto interessato invece che al collega.', 'lavoro', 'it', 'approvato'),
('Rispondere "presente" quando il professore chiama un altro nome durante l''appello.', 'lavoro', 'it', 'approvato'),
('Salvare il documento senza salvarlo e perdere tre ore di lavoro.', 'lavoro', 'it', 'approvato'),
('Fare una domanda in riunione e capire dalla reazione di tutti che la risposta era ovvia.', 'lavoro', 'it', 'approvato'),
('Dimenticarsi di essere in muto durante una call e parlare per due minuti nel vuoto.', 'lavoro', 'it', 'approvato'),
('Stare in videocall con la camera accesa e fare qualcosa che non avresti mai fatto con la camera accesa.', 'lavoro', 'it', 'approvato'),
('Mandare per errore un messaggio con insulti al gruppo di lavoro invece che al collega fidato.', 'lavoro', 'it', 'approvato'),
('Rispondere a una mail importante con "grazie" invece di un testo elaborato e poi non poter rimandare.', 'lavoro', 'it', 'approvato'),
('Fare una pausa caffè lunghissima e tornare trovando il capo alla scrivania.', 'lavoro', 'it', 'approvato'),
('Presentare un''analisi sbagliata con sicurezza assoluta e scoprirlo solo quando qualcuno ti ferma.', 'lavoro', 'it', 'approvato'),
('Tenere la telecamera della videocall puntata sul soffitto per tutta la riunione.', 'lavoro', 'it', 'approvato'),
('Sbagliare nome al capo in un momento formale e correggersi rendendolo peggio.', 'lavoro', 'it', 'approvato'),
('Inviare una presentazione con i commenti "SISTEMARE QUESTA PARTE" ancora visibili.', 'lavoro', 'it', 'approvato'),
('Fare mute/unmute durante una call così tante volte da perdere il filo del discorso.', 'lavoro', 'it', 'approvato'),
('Aprire il documento sbagliato durante una condivisione schermo e non riuscire a trovare quello giusto.', 'lavoro', 'it', 'approvato'),
('Mandare "arrivoooo" al gruppo di lavoro invece che a un amico.', 'lavoro', 'it', 'approvato'),
('Promettere una deadline impossibile e doverla rispettare.', 'lavoro', 'it', 'approvato'),
('Essere presentato a un cliente come esperto di qualcosa di cui non sai niente.', 'lavoro', 'it', 'approvato'),
('Fare lo stesso errore due volte davanti alla stessa persona.', 'lavoro', 'it', 'approvato'),
('Mangiare in ufficio qualcosa di odoroso e vedere le facce dei colleghi.', 'lavoro', 'it', 'approvato'),

-- APPUNTAMENTI (24)
('Arrivare al primo appuntamento e non riconoscere la persona dalle foto.', 'appuntamenti', 'it', 'approvato'),
('Fare una battuta che cade nel vuoto al primo appuntamento e dover far finta che non fosse una battuta.', 'appuntamenti', 'it', 'approvato'),
('Raccontare la storia più divertente della tua vita e vedere l''altro che non ride neanche un po''.', 'appuntamenti', 'it', 'approvato'),
('Arrivare prima al ristorante del primo appuntamento e non sapere dove guardare per dieci minuti.', 'appuntamenti', 'it', 'approvato'),
('Fare una domanda già fatta cinque minuti prima perché non stavi ascoltando.', 'appuntamenti', 'it', 'approvato'),
('Dire il nome sbagliato. Correggerti. Peggiorare.', 'appuntamenti', 'it', 'approvato'),
('Parlare del tuo ex per tutto il tempo senza accorgertene.', 'appuntamenti', 'it', 'approvato'),
('Incastrarsi con chi paga il conto in un silenzio imbarazzante di trenta secondi.', 'appuntamenti', 'it', 'approvato'),
('Decidere di essere spontaneo e dire la prima cosa che ti viene in mente che non dovevi dire.', 'appuntamenti', 'it', 'approvato'),
('Ordinare la cosa più difficile da mangiare elegantemente e doverla mangiare elegantemente.', 'appuntamenti', 'it', 'approvato'),
('Fare una scena di gelosia per qualcuno che non era nemmeno un tuo partner.', 'appuntamenti', 'it', 'approvato'),
('Aspettare il messaggio del giorno dopo che non arriva mai.', 'appuntamenti', 'it', 'approvato'),
('Scoprire che la persona con cui ti stai frequentando conosce benissimo tutti i tuoi amici.', 'appuntamenti', 'it', 'approvato'),
('Usare un termine affettuoso troppo presto e vedere la reazione.', 'appuntamenti', 'it', 'approvato'),
('Cercare di sembrare casual mentre in realtà hai pianificato tutto nei minimi dettagli.', 'appuntamenti', 'it', 'approvato'),
('Finire le cose da dire dopo venti minuti e avere ancora due ore di cena davanti.', 'appuntamenti', 'it', 'approvato'),
('Scoprire di avere gli stessi gusti in comune con qualcuno e stare insieme tre settimane finché finiscono gli argomenti.', 'appuntamenti', 'it', 'approvato'),
('Scrivere un messaggio perfetto, attendersi una risposta perfetta, ricevere "ok".', 'appuntamenti', 'it', 'approvato'),
('Fare come se ti importasse zero e poi controllare il telefono ogni tre minuti.', 'appuntamenti', 'it', 'approvato'),
('Incontrare il tuo ex quando sei nel mezzo del momento più imbarazzante della tua vita.', 'appuntamenti', 'it', 'approvato'),
('Mettere troppa roba sulla chat troppo presto e poi pentirtene alle tre di notte.', 'appuntamenti', 'it', 'approvato'),
('Dimenticare per un secondo il nome della persona con cui stai parlando da un''ora.', 'appuntamenti', 'it', 'approvato'),
('Fare il romantico e scoprire che l''altro è allergico a quello che hai scelto.', 'appuntamenti', 'it', 'approvato'),
('Costruire un''aspettativa enorme attorno a qualcosa e poi avere tutto esattamente come al solito.', 'appuntamenti', 'it', 'approvato');
