-- Batch 150 nuovi disagi — IlDisagio
-- Generati il 2026-03-22

INSERT INTO disagi (testo, categoria, lingua, stato) VALUES

-- SOCIALE (25)
('Saluti qualcuno per strada convinto di conoscerlo e a metà gesto capisci che è un perfetto estraneo.', 'sociale', 'it', 'approvato'),
('Ridi a una battuta che non hai capito e ti chiedono di spiegarla.', 'sociale', 'it', 'approvato'),
('Dici "anche io" a qualcosa che non hai mai fatto solo per non essere tagliato fuori dalla conversazione.', 'sociale', 'it', 'approvato'),
('Arrivi a una festa, l''unica persona che conosci è sparita, e rimani lì con il bicchiere in mano.', 'sociale', 'it', 'approvato'),
('Salutativi, andate nella stessa direzione e camminate fianco a fianco in silenzio per cinque minuti.', 'sociale', 'it', 'approvato'),
('Esaurisci gli argomenti ma il silenzio è insostenibile, quindi ricominci con "comunque...".', 'sociale', 'it', 'approvato'),
('Ti presentano qualcuno e dimentichi il nome dopo tre secondi, poi devi evitare di chiamarlo per tutto il pomeriggio.', 'sociale', 'it', 'approvato'),
('Fai una battuta in gruppo. Silenzio. Provi a spiegarla. Silenzio ancora più pesante.', 'sociale', 'it', 'approvato'),
('Scopri di aver usato una parola sbagliata per tutta la vita e lo realizzi davanti a sei persone.', 'sociale', 'it', 'approvato'),
('Urli il nome di qualcuno per strada. Si gira. Non è chi pensavi. Continuate a fissarvi.', 'sociale', 'it', 'approvato'),
('Abbracci qualcuno che ti stava porgendo la mano. Ora siete entrambi bloccati a metà gesto.', 'sociale', 'it', 'approvato'),
('Rispondi "bene grazie" senza capire cosa ti hanno detto, e poi vedi la faccia dell''altro.', 'sociale', 'it', 'approvato'),
('Ti viene una risata incontrollabile nel momento più serio possibile. Più cerchi di trattenerti, peggio va.', 'sociale', 'it', 'approvato'),
('Fai finta di ricordare una storia che ti stanno raccontando per la quarta volta. Annuisci. Ridi al momento giusto.', 'sociale', 'it', 'approvato'),
('Ti accorgi di star fissando qualcuno. Avete il contatto visivo. Nessuno dei due distoglie lo sguardo abbastanza in fretta.', 'sociale', 'it', 'approvato'),
('Dici "ci sentiamo presto" sapendo benissimo che non vi sentite da due anni e non cambierà.', 'sociale', 'it', 'approvato'),
('Sei l''unico del gruppo a non aver visto quella serie. La conversazione va avanti senza di te per venti minuti.', 'sociale', 'it', 'approvato'),
('Applaudi troppo presto alla fine di un concerto. Parte un''altra canzone. Abbassi le mani lentamente.', 'sociale', 'it', 'approvato'),
('Non senti cosa ha detto qualcuno per la terza volta. Annuisci. Era una domanda.', 'sociale', 'it', 'approvato'),
('Arrivi in anticipo a un appuntamento. Sei lì da dieci minuti. Non sai dove mettere le mani.', 'sociale', 'it', 'approvato'),
('Ti fanno un complimento e non sai rispondere. Dici "anche tu". Non ha senso. Lo sai.', 'sociale', 'it', 'approvato'),
('Esci dal bagno di qualcuno e ci metti trenta secondi a capire come aprire la porta.', 'sociale', 'it', 'approvato'),
('Ordini la stessa cosa di tutti al ristorante per non sembrare difficile, anche se non ti va.', 'sociale', 'it', 'approvato'),
('Fai una foto a qualcosa di interessante e due persone pensano che stai fotografando loro.', 'sociale', 'it', 'approvato'),
('Tieni la porta aperta per qualcuno che è troppo lontano. Aspetti. Lui accelera. Entrambi imbarazzati.', 'sociale', 'it', 'approvato'),

-- DIGITALE (25)
('Mandi un messaggio al gruppo sbagliato. Lo leggi subito dopo aver premuto invio.', 'digitale', 'it', 'approvato'),
('Parli per due minuti in videochiamata con il microfono in muto. Tutti ti guardano in attesa.', 'digitale', 'it', 'approvato'),
('Metti like a una foto di tre anni fa perché stavi scorrendo il profilo di qualcuno troppo in profondità.', 'digitale', 'it', 'approvato'),
('Apri una chat per sbaglio. Ora quella persona pensa che tu la stia ignorando.', 'digitale', 'it', 'approvato'),
('Scrivi un messaggio lungo e riflessivo. Risposta: "ok".', 'digitale', 'it', 'approvato'),
('Aggiorni la pagina per sbaglio mentre stavi scrivendo un testo lunghissimo non salvato.', 'digitale', 'it', 'approvato'),
('L''autocorrettore ti cambia una parola nel momento peggiore possibile e lo noti solo dopo aver inviato.', 'digitale', 'it', 'approvato'),
('Condividi lo schermo in una call e ricordi troppo tardi che hai notifiche imbarazzanti visibili.', 'digitale', 'it', 'approvato'),
('Lasci una conversazione in sospeso per rispondere "con calma". Passano sei giorni.', 'digitale', 'it', 'approvato'),
('Il tuo telefono legge ad alta voce una notifica privata in un posto silenzioso.', 'digitale', 'it', 'approvato'),
('Clicchi "Rispondi a tutti" invece di "Rispondi" su una email di lavoro.', 'digitale', 'it', 'approvato'),
('Metti una storia su Instagram pensando fosse per qualcuno di specifico. La vedono tutti.', 'digitale', 'it', 'approvato'),
('Stai scrivendo a qualcuno. Vedi "sta scrivendo..." che appare e scompare per dieci minuti. Poi niente.', 'digitale', 'it', 'approvato'),
('Il tuo browser fa autocompletamento con qualcosa che non avresti mai voluto che si vedesse.', 'digitale', 'it', 'approvato'),
('Rispondi a un messaggio di tre settimane fa come se fosse fresco. L''altro non risponde.', 'digitale', 'it', 'approvato'),
('Salvi un numero senza nome. Un mese dopo non sai di chi è e non puoi chiederlo.', 'digitale', 'it', 'approvato'),
('Il tuo assistente vocale si attiva da solo nel mezzo di una conversazione importante.', 'digitale', 'it', 'approvato'),
('Scarichi un file. Non riesci a trovarlo da nessuna parte. Cerchi per venti minuti.', 'digitale', 'it', 'approvato'),
('Guardi le storie di qualcuno e lui è sempre primo nella lista dei visualizzatori delle tue.', 'digitale', 'it', 'approvato'),
('Scrivi al numero sbagliato pensando di scrivere a qualcun altro. Te ne accorgi dopo tre messaggi.', 'digitale', 'it', 'approvato'),
('Il wifi finisce nel momento più cruciale. Ricarichi la pagina. Hai perso tutto.', 'digitale', 'it', 'approvato'),
('Commenti un post su Instagram convinto sia recente. Era del 2021.', 'digitale', 'it', 'approvato'),
('Mandi una foto nel gruppo di lavoro che era per un''altra chat.', 'digitale', 'it', 'approvato'),
('Il telefono cade rumorosamente sul pavimento di un posto completamente silenzioso.', 'digitale', 'it', 'approvato'),
('Entri in videochiamata e ci metti cinque minuti a capire che sei fuori inquadratura.', 'digitale', 'it', 'approvato'),

-- RELAZIONALE (25)
('Il tuo migliore amico si mette con qualcuno che non ti sta simpatico e devi fare il tifo.', 'relazionale', 'it', 'approvato'),
('Senti che qualcuno sta aspettando che tu chieda come sta per potertelo dire.', 'relazionale', 'it', 'approvato'),
('Qualcuno ti dice "ti devo dire una cosa" e poi non te la dice. Aspetti tutto il giorno.', 'relazionale', 'it', 'approvato'),
('Sai che una persona sta mentendo ma non puoi dirlo senza rivelare come lo sai.', 'relazionale', 'it', 'approvato'),
('Un amico ti chiede un parere onesto su qualcosa che ha già deciso. Vuole solo conferme.', 'relazionale', 'it', 'approvato'),
('Stai litigando con qualcuno e nel mezzo realizzi che ha ragione. È troppo tardi per ammetterlo.', 'relazionale', 'it', 'approvato'),
('Incontri l''ex di un amico. Non sai se salutarlo o fare finta di non vederlo.', 'relazionale', 'it', 'approvato'),
('Ti viene detto un segreto che avresti preferito non sapere e ora non puoi fare finta di niente.', 'relazionale', 'it', 'approvato'),
('Continui a scrivere e cancellare un messaggio importante. Non lo mandi mai.', 'relazionale', 'it', 'approvato'),
('Qualcuno ti fa un regalo che non ti piace. Devi simulare entusiasmo per dieci minuti.', 'relazionale', 'it', 'approvato'),
('Ti stanno raccontando la stessa storia per la quarta volta. Devi fingerti sorpreso al momento giusto.', 'relazionale', 'it', 'approvato'),
('Annunci qualcosa di importante nella tua vita. Qualcuno cambia subito argomento.', 'relazionale', 'it', 'approvato'),
('Il tuo migliore amico fa amicizia con qualcuno che non conosci. Ti senti lentamente sostituito.', 'relazionale', 'it', 'approvato'),
('Devi dire a qualcuno una cosa difficile. Ci pensi così tanto da non dirla mai.', 'relazionale', 'it', 'approvato'),
('Litighi con qualcuno. Dimentichi di cosa stavate litigando. Sei ancora arrabbiato lo stesso.', 'relazionale', 'it', 'approvato'),
('Scopri di essere l''unico del gruppo a non sapere una cosa che tutti davano per scontata.', 'relazionale', 'it', 'approvato'),
('Un amico ti tagga in una foto brutta. Aspetti tre ore prima di chiedere di toglierla.', 'relazionale', 'it', 'approvato'),
('Scopri che quello che pensavi fosse un segreto tra voi due lo sapevano già tutti.', 'relazionale', 'it', 'approvato'),
('Fingi di ricordare un aneddoto che ti raccontano su di te. Non lo ricordi affatto.', 'relazionale', 'it', 'approvato'),
('Senti che stai perdendo un''amicizia lentamente. Nessuno dei due lo dice ad alta voce.', 'relazionale', 'it', 'approvato'),
('Un amico ti presenta i suoi nuovi amici. Hai la sensazione di dover fare un provino.', 'relazionale', 'it', 'approvato'),
('Qualcuno ti chiede perché non sei venuto a una cosa a cui non eri stato invitato.', 'relazionale', 'it', 'approvato'),
('Qualcuno ti dà del tu quando gli hai dato del lei. Non sai come tornare indietro.', 'relazionale', 'it', 'approvato'),
('Ti rendi conto che stai aspettando un messaggio da qualcuno che probabilmente non pensa a te.', 'relazionale', 'it', 'approvato'),
('Fai una cosa gentile e la persona non se ne accorge. La fai notare e sembra che tu volessi il merito.', 'relazionale', 'it', 'approvato'),

-- PUBBLICO (25)
('Inciampi per strada. Ti guardi intorno. Troppe persone hanno visto.', 'pubblico', 'it', 'approvato'),
('Entri nel posto sbagliato. Non puoi uscire subito perché sembrerebbe ancora più strano.', 'pubblico', 'it', 'approvato'),
('Il tuo stomaco fa un rumore fortissimo in un posto completamente silenzioso.', 'pubblico', 'it', 'approvato'),
('Cammini verso una porta automatica che non si apre. Ci sono persone che guardano.', 'pubblico', 'it', 'approvato'),
('Paghi al bar. La carta viene rifiutata. C''è la fila.', 'pubblico', 'it', 'approvato'),
('Non trovi subito i soldi al supermercato. Il cassiere aspetta. La fila aspetta. Tutti aspettano.', 'pubblico', 'it', 'approvato'),
('Esci da un negozio e scatta l''allarme antitaccheggio. Hai pagato tutto. Tutti si girano.', 'pubblico', 'it', 'approvato'),
('Ti siedi accanto a qualcuno sul treno. Deve scendere alla fermata successiva.', 'pubblico', 'it', 'approvato'),
('Cerchi di sembrare occupato al telefono in un posto imbarazzante. Qualcuno capisce che stai fingendo.', 'pubblico', 'it', 'approvato'),
('Il posto dove vuoi sederti al bar ha un cartello "riservato" che non avevi visto.', 'pubblico', 'it', 'approvato'),
('Non senti il prezzo al bar. Dici "sì". Non sai quanto stai pagando.', 'pubblico', 'it', 'approvato'),
('Ti accorgi di parlare troppo forte sul treno solo quando tutti si sono già girati.', 'pubblico', 'it', 'approvato'),
('Fai cadere qualcosa in un negozio. Cercando di raccoglierlo, fai cadere altro.', 'pubblico', 'it', 'approvato'),
('L''ombrello si ribalta con il vento in mezzo alla gente. Lotti con esso per trenta secondi.', 'pubblico', 'it', 'approvato'),
('Sorridi a qualcuno che non ti sta sorridendo. Aveva solo un''espressione neutra.', 'pubblico', 'it', 'approvato'),
('Ti svegli sul treno alla fermata sbagliata. Le porte si chiudono.', 'pubblico', 'it', 'approvato'),
('Stai cercando qualcosa nella borsa da cinque minuti con tutti che guardano.', 'pubblico', 'it', 'approvato'),
('Ordini in un locale straniero e pronunci tutto male. Il cameriere ti corregge con gentilezza.', 'pubblico', 'it', 'approvato'),
('Entri in un negozio, guardi in giro, non compri niente, ed esci sotto lo sguardo del commesso.', 'pubblico', 'it', 'approvato'),
('Scendi dall''autobus prima che si fermi del tutto. Barcollhi. Qualcuno ha visto.', 'pubblico', 'it', 'approvato'),
('Premi il piano sbagliato in ascensore davanti ad altre persone e aspetti in silenzio.', 'pubblico', 'it', 'approvato'),
('Parli da solo mentre cammini con gli auricolari. Qualcuno pensa che stai parlando con lui.', 'pubblico', 'it', 'approvato'),
('Ti si rovesciano le buste della spesa per strada. I pomodori rotolano ovunque.', 'pubblico', 'it', 'approvato'),
('Telefoni a qualcuno, lui risponde subito, e tu hai dimenticato perché hai chiamato.', 'pubblico', 'it', 'approvato'),
('Aspetti l''ascensore. Si aprono le porte. È già pieno. Aspetti il prossimo fingendo che fosse il piano.', 'pubblico', 'it', 'approvato'),

-- LAVORO (25)
('Entri in una riunione e capisci subito di non dover essere lì. Non puoi uscire.', 'lavoro', 'it', 'approvato'),
('Il capo ti fa una domanda durante la call. Non stavi ascoltando. Ci sono tre secondi di silenzio.', 'lavoro', 'it', 'approvato'),
('Mandi un''email urgente. Trovi un errore di battitura nell''oggetto subito dopo.', 'lavoro', 'it', 'approvato'),
('Fai una battuta in riunione. Silenzio. Il capo dice "comunque..." e va avanti.', 'lavoro', 'it', 'approvato'),
('Arrivi tardi a una riunione che era già finita in anticipo. Tutti stanno uscendo.', 'lavoro', 'it', 'approvato'),
('Dici "concordo pienamente". Ti chiedono di espandere il concetto. Non sai cosa stavi concordando.', 'lavoro', 'it', 'approvato'),
('Scrivi "Cordiali saluti" a un collega con cui dai del tu da tre anni.', 'lavoro', 'it', 'approvato'),
('Mandi un''email di risposta e ti accorgi dopo che era in CC anche il diretto interessato.', 'lavoro', 'it', 'approvato'),
('Fingi di prendere appunti in riunione. Il capo ti chiede di leggere quello che hai scritto.', 'lavoro', 'it', 'approvato'),
('Devi spiegare cosa fai esattamente nel tuo lavoro. Ci metti cinque minuti. Non sei convinto nemmeno tu.', 'lavoro', 'it', 'approvato'),
('Il collega fa una proposta identica alla tua di dieci minuti prima. Il capo la loda.', 'lavoro', 'it', 'approvato'),
('Rispondi "buongiorno" a qualcuno alle 14:00 per abitudine. Nessuno fa finta di niente.', 'lavoro', 'it', 'approvato'),
('Sei in muto durante la call. Lo scopri solo quando tutti ti guardano in attesa da trenta secondi.', 'lavoro', 'it', 'approvato'),
('Mandi in stampa un documento. Era quello sbagliato. Lo scopri quando esci dalla stampante.', 'lavoro', 'it', 'approvato'),
('Fai finta di lavorare quando passa il capo. Lui lo sa. Tu lo sai che lui lo sa.', 'lavoro', 'it', 'approvato'),
('Devi fare una presentazione. Il pc si blocca davanti a tutti. Aspetti in silenzio.', 'lavoro', 'it', 'approvato'),
('Chiedi a un collega come si chiama qualcuno che lavora lì da più anni di te.', 'lavoro', 'it', 'approvato'),
('Ti scappa un "ciao mamma" al telefono con un cliente.', 'lavoro', 'it', 'approvato'),
('L''unica cosa che ricordi della riunione di un''ora è che durava troppo.', 'lavoro', 'it', 'approvato'),
('Proponi un''idea già scartata sei mesi fa. Tutti la ricordano tranne te.', 'lavoro', 'it', 'approvato'),
('Dici al capo "ci penso io" per qualcosa che non hai idea di come fare.', 'lavoro', 'it', 'approvato'),
('Mandi un messaggio alla chat di lavoro che era per quella degli amici.', 'lavoro', 'it', 'approvato'),
('Firmi un documento. Un mese dopo non ricordi di averlo firmato quando te ne chiedono conto.', 'lavoro', 'it', 'approvato'),
('Arrivi in ufficio vestito in modo completamente sbagliato per la riunione importante di quel giorno.', 'lavoro', 'it', 'approvato'),
('Hai lavorato su un file per un''ora. Non lo hai salvato. Il computer si spegne.', 'lavoro', 'it', 'approvato'),

-- APPUNTAMENTI (25)
('Arrivi al primo appuntamento e non riconosci la persona dalla foto del profilo.', 'appuntamenti', 'it', 'approvato'),
('Fai una battuta. L''altro ride troppo, troppo a lungo, troppo gentilmente.', 'appuntamenti', 'it', 'approvato'),
('Ordini qualcosa di difficile da mangiare. Te ne penti per tutto il pasto.', 'appuntamenti', 'it', 'approvato'),
('Il conto arriva. Nessuno dei due si muove. Aspettate entrambi che l''altro faccia qualcosa.', 'appuntamenti', 'it', 'approvato'),
('Mandi un vocale romantico. In sottofondo si sente la televisione con uno spot.', 'appuntamenti', 'it', 'approvato'),
('Ti presenti con lo stesso vestito della foto del profilo. Sembra che non ne hai altri.', 'appuntamenti', 'it', 'approvato'),
('Finite gli argomenti di conversazione a metà secondo aperitivo. Il silenzio dura troppo.', 'appuntamenti', 'it', 'approvato'),
('Cerchi di essere disinvolto. Rovesci qualcosa sul tavolo.', 'appuntamenti', 'it', 'approvato'),
('L''appuntamento va bene. Entrambi fingete di non volervi rivedere subito per non sembrare disperati.', 'appuntamenti', 'it', 'approvato'),
('Ti chiede della tua ex. Dici "è una storia lunga". Poi gliela racconti tutta.', 'appuntamenti', 'it', 'approvato'),
('Fine dell''appuntamento: stretta di mano? Bacio sulla guancia? Abbraccio? Fate tutti e tre male.', 'appuntamenti', 'it', 'approvato'),
('Il tuo appuntamento è in ritardo. Aspetti venti minuti. Non sai cosa fare con le mani.', 'appuntamenti', 'it', 'approvato'),
('Dici "adoro quel film" su qualcosa che non hai mai visto. Ti chiede il film preferito.', 'appuntamenti', 'it', 'approvato'),
('Stai cercando di sembrare interessante. Realizzi di star raccontando la stessa storia di prima.', 'appuntamenti', 'it', 'approvato'),
('Vai al bagno durante l''appuntamento. Non sai quanto tempo stare via per non sembrare strano.', 'appuntamenti', 'it', 'approvato'),
('Non capisci se vi state salutando o continuate la serata. Restate fermi sul marciapiede.', 'appuntamenti', 'it', 'approvato'),
('L''altro ordina l''acqua. Tu hai già chiesto il vino. Ora sembra che tu abbia un problema.', 'appuntamenti', 'it', 'approvato'),
('Mandi un messaggio doppio per controllare se ha letto. Lo vedi online. Non risponde.', 'appuntamenti', 'it', 'approvato'),
('Fai una domanda e realizzi che l''avresti già saputo se avessi letto il profilo.', 'appuntamenti', 'it', 'approvato'),
('Il ristorante che avevi prenotato è chiuso. Devi improvvisare un piano B davanti a lui/lei.', 'appuntamenti', 'it', 'approvato'),
('Torni a casa e rileggi tutta la conversazione cercando segnali nascosti in ogni messaggio.', 'appuntamenti', 'it', 'approvato'),
('Aspetti esattamente il numero giusto di ore prima di scrivere. Nemmeno tu sai quale sia.', 'appuntamenti', 'it', 'approvato'),
('Dici una cosa che pensavi fosse spiritosa. Lui/lei la prende sul serio. Ora devi stare al gioco.', 'appuntamenti', 'it', 'approvato'),
('Alla fine dite "dobbiamo rifarlo". Nessuno dei due scrive. Passano tre settimane.', 'appuntamenti', 'it', 'approvato'),
('Ti piace così tanto che torni a casa e guardi di nuovo il profilo. Metti like per sbaglio.', 'appuntamenti', 'it', 'approvato');
